import type {
  User,
  Vehicle,
  TrafficLaw,
  Violation,
  State,
  TrafficAlert,
  Document,
  Dashboard,
  Challan,
  ViolationType,
} from '@/types'

export const currentUser: User = {
  id: 'user_001',
  name: 'Rajesh Kumar',
  email: 'rajesh.kumar@example.com',
  role: 'citizen',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh',
  location: 'Bangalore, Karnataka',
  language: 'English',
}

export const vehicles: Vehicle[] = [
  {
    id: 'vehicle_001',
    registrationNumber: 'KA-05-AB-1234',
    vehicleType: 'car',
    manufacturer: 'Hyundai',
    model: 'Creta',
    year: 2022,
    color: 'Silver',
    fuelType: 'diesel',
    insuranceExpiry: '2025-06-15',
    pollutionCertificateExpiry: '2024-12-30',
  },
  {
    id: 'vehicle_002',
    registrationNumber: 'KA-12-CD-5678',
    vehicleType: 'motorcycle',
    manufacturer: 'Honda',
    model: 'CB350',
    year: 2023,
    color: 'Black',
    fuelType: 'petrol',
    insuranceExpiry: '2026-03-20',
    pollutionCertificateExpiry: '2025-08-15',
  },
]

export const trafficLaws: TrafficLaw[] = [
  {
    id: 'law_001',
    state: 'Karnataka',
    title: 'Speeding Violation - Beyond 60 km/h in residential area',
    description:
      'Driving at a speed exceeding the prescribed speed limit in residential areas.',
    fineAmount: 500,
    violationType: 'Speeding',
    category: 'Moving Violation',
    amendmentDate: '2023-01-15',
    source: 'Motor Vehicles Act, 1988 - Section 188',
    applicableVehicles: ['car', 'motorcycle', 'commercial'],
    relatedSections: ['188', '189'],
  },
  {
    id: 'law_002',
    state: 'Karnataka',
    title: 'Dangerous Driving',
    description: 'Driving in a manner which is dangerous to public safety.',
    fineAmount: 1000,
    violationType: 'Dangerous Driving',
    category: 'Criminal Offense',
    source: 'Motor Vehicles Act, 1988 - Section 336',
    applicableVehicles: ['car', 'motorcycle', 'commercial'],
    relatedSections: ['336'],
  },
  {
    id: 'law_003',
    state: 'Karnataka',
    title: 'Helmet Violation',
    description: 'Riding motorcycle without proper safety helmet.',
    fineAmount: 100,
    violationType: 'Safety Equipment',
    category: 'Safety Violation',
    source: 'Motor Vehicles Act, 1988 - Section 129',
    applicableVehicles: ['motorcycle'],
    relatedSections: ['129'],
  },
  {
    id: 'law_004',
    state: 'Maharashtra',
    title: 'Traffic Signal Violation',
    description: 'Violating traffic signal rules and crossing red light.',
    fineAmount: 800,
    violationType: 'Traffic Signal',
    category: 'Traffic Violation',
    source: 'Motor Vehicles Act, 1988 - Section 177',
    applicableVehicles: ['car', 'motorcycle', 'commercial'],
    relatedSections: ['177'],
  },
  {
    id: 'law_005',
    state: 'Delhi',
    title: 'No Parking Zone Violation',
    description: 'Parking vehicle in prohibited areas.',
    fineAmount: 600,
    violationType: 'Parking',
    category: 'Administrative Violation',
    source: 'Motor Vehicles Act, 1988 - Section 173',
    applicableVehicles: ['car'],
    relatedSections: ['173'],
  },
]

export const violations: Violation[] = [
  {
    id: 'violation_001',
    type: 'Speeding',
    location: 'Outer Ring Road, Bangalore',
    date: '2024-01-20',
    severity: 'medium',
    fineAmount: 500,
    description: 'Driving at 75 km/h in 60 km/h zone',
    state: 'Karnataka',
    officer: 'Officer Sharma',
    status: 'pending',
  },
  {
    id: 'violation_002',
    type: 'Helmet Violation',
    location: 'Brigade Road, Bangalore',
    date: '2024-01-15',
    severity: 'low',
    fineAmount: 100,
    description: 'Riding motorcycle without helmet',
    state: 'Karnataka',
    status: 'resolved',
  },
  {
    id: 'violation_003',
    type: 'Traffic Signal',
    location: 'Silk Board Junction, Bangalore',
    date: '2024-01-10',
    severity: 'high',
    fineAmount: 800,
    description: 'Crossing red light',
    state: 'Karnataka',
    officer: 'Officer Patel',
    status: 'pending',
  },
  {
    id: 'violation_004',
    type: 'Dangerous Driving',
    location: 'Whitefield, Bangalore',
    date: '2023-12-25',
    severity: 'critical',
    fineAmount: 1000,
    description: 'Weaving between lanes and rash driving',
    state: 'Karnataka',
    status: 'resolved',
  },
]

export const challans: Challan[] = [
  {
    id: 'challan_001',
    violationId: 'violation_001',
    citizenName: 'Rajesh Kumar',
    registrationNumber: 'KA-05-AB-1234',
    violations: [
      { id: 'v1', name: 'Speeding', baseFine: 500, repeatOffenseFactor: 1 },
    ],
    totalFine: 500,
    issuedDate: '2024-01-20',
    dueDate: '2024-02-20',
    status: 'pending',
  },
  {
    id: 'challan_002',
    violationId: 'violation_003',
    citizenName: 'Rajesh Kumar',
    registrationNumber: 'KA-05-AB-1234',
    violations: [
      { id: 'v2', name: 'Traffic Signal', baseFine: 800, repeatOffenseFactor: 1 },
    ],
    totalFine: 800,
    issuedDate: '2024-01-10',
    dueDate: '2024-02-10',
    status: 'pending',
    paymentMethod: 'online',
  },
]

export const states: State[] = [
  {
    code: 'KA',
    name: 'Karnataka',
    region: 'Southern India',
    capital: 'Bangalore',
    laws: trafficLaws.filter((l) => l.state === 'Karnataka'),
  },
  {
    code: 'MH',
    name: 'Maharashtra',
    region: 'Western India',
    capital: 'Mumbai',
    laws: trafficLaws.filter((l) => l.state === 'Maharashtra'),
  },
  {
    code: 'DL',
    name: 'Delhi',
    region: 'Northern India',
    capital: 'Delhi',
    laws: trafficLaws.filter((l) => l.state === 'Delhi'),
  },
]

export const trafficAlerts: TrafficAlert[] = [
  {
    id: 'alert_001',
    type: 'enforcement',
    location: 'Silk Board Junction, Bangalore',
    severity: 'high',
    message: 'Active police enforcement zone ahead. Speed limit: 40 km/h',
    timestamp: '2024-01-22T10:30:00',
    coordinates: { lat: 12.9352, lng: 77.6244 },
  },
  {
    id: 'alert_002',
    type: 'accident',
    location: 'Outer Ring Road, Bangalore',
    severity: 'critical',
    message: 'Major accident reported. Avoid area and use alternate routes.',
    timestamp: '2024-01-22T11:15:00',
    coordinates: { lat: 12.97, lng: 77.68 },
  },
  {
    id: 'alert_003',
    type: 'congestion',
    location: 'Brigade Road, Bangalore',
    severity: 'medium',
    message: 'Heavy traffic congestion. Expected delay: 45 minutes',
    timestamp: '2024-01-22T12:00:00',
    coordinates: { lat: 12.974, lng: 77.6014 },
  },
  {
    id: 'alert_004',
    type: 'roadwork',
    location: 'Koramangala, Bangalore',
    severity: 'medium',
    message: 'Road construction ongoing. Lane closure: 2 hours',
    timestamp: '2024-01-22T09:00:00',
    coordinates: { lat: 12.9353, lng: 77.6245 },
  },
  {
    id: 'alert_005',
    type: 'weather',
    location: 'Bangalore',
    severity: 'low',
    message: 'Light rain expected. Drive safely with reduced speed.',
    timestamp: '2024-01-22T08:30:00',
  },
]

export const documents: Document[] = [
  {
    id: 'doc_001',
    type: 'license',
    name: 'Driving License - KA',
    url: '/docs/license.pdf',
    expiryDate: '2030-05-15',
    uploadedDate: '2020-05-15',
    status: 'valid',
  },
  {
    id: 'doc_002',
    type: 'registration',
    name: 'Vehicle Registration - KA-05-AB-1234',
    url: '/docs/registration.pdf',
    expiryDate: '2026-12-31',
    uploadedDate: '2021-12-31',
    status: 'valid',
  },
  {
    id: 'doc_003',
    type: 'insurance',
    name: 'Car Insurance - Bajaj Allianz',
    url: '/docs/insurance.pdf',
    expiryDate: '2025-06-15',
    uploadedDate: '2024-06-15',
    status: 'valid',
  },
  {
    id: 'doc_004',
    type: 'pollution',
    name: 'Pollution Certificate - BS6',
    url: '/docs/pollution.pdf',
    expiryDate: '2024-12-30',
    uploadedDate: '2023-12-30',
    status: 'expiring',
  },
]

export const dashboardData: Dashboard = {
  userId: 'user_001',
  totalFines: 1300,
  pendingChallan: 2,
  complianceScore: 65,
  recentViolations: violations.slice(0, 3),
  trafficAlerts: trafficAlerts.slice(0, 3),
  aiInsights: [
    {
      id: 'insight_001',
      type: 'warning',
      title: 'Speeding Pattern Detected',
      description:
        'Your speeding incidents have increased by 40% in the past month. Consider maintaining speed limits.',
      actionItems: [
        'Check speed limits before driving',
        'Use cruise control on highways',
      ],
      confidence: 0.85,
      timestamp: '2024-01-22T10:00:00',
    },
    {
      id: 'insight_002',
      type: 'recommendation',
      title: 'Traffic-Free Route Available',
      description:
        'Based on current traffic and your preferences, take NH47 instead of ORR for 30% faster commute.',
      actionItems: ['Accept recommendation'],
      confidence: 0.92,
      timestamp: '2024-01-22T11:30:00',
    },
    {
      id: 'insight_003',
      type: 'info',
      title: 'Pollution Certificate Expiring Soon',
      description:
        'Your vehicle pollution certificate expires on 2024-12-30. Schedule renewal soon.',
      actionItems: ['Schedule appointment', 'Find nearby test center'],
      confidence: 1,
      timestamp: '2024-01-22T09:00:00',
    },
  ],
}

export const analyticsData = {
  totalViolations: 15234,
  avgFineAmount: 652,
  complianceRate: 72,
  enforcementZones: 42,
  accidentHotspots: 18,
  trends: [
    { date: 'Jan 1', violations: 120, accidents: 8, fines: 78400 },
    { date: 'Jan 8', violations: 135, accidents: 12, fines: 88200 },
    { date: 'Jan 15', violations: 98, accidents: 5, fines: 63856 },
    { date: 'Jan 22', violations: 156, accidents: 9, fines: 101712 },
    { date: 'Feb 1', violations: 142, accidents: 10, fines: 92584 },
    { date: 'Feb 8', violations: 168, accidents: 14, fines: 109536 },
    { date: 'Feb 15', violations: 145, accidents: 11, fines: 94540 },
  ],
}
